version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    tty: true
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
